// AGENTS.md, written into the mirror root for agents and humans. It carries a version marker and
// is rewritten whenever the marker is behind.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { CONFIG_FILE, STATE_DIR } from "./config.ts";

export const AGENTS_VERSION = 1;

export const AGENTS_MD = `<!-- planka-sync agents v${AGENTS_VERSION}; generated by planka-sync, edits are overwritten -->
# This directory mirrors a Planka project

Every board, list and card of one Planka project lives here as directories and files. Planka is
the system of record; these files are the editing surface. Edit, create, move or delete files,
then run \`npx planka-sync\` in this directory: it pushes your changes to Planka, pulls Planka's
changes to disk, and prints one line per file it touched. Nothing reaches Planka until you run it.

## Layout

\`\`\`
${CONFIG_FILE}                       which server and project (safe to commit)
<board>/board.yaml                      lists (dir, name, type, id), labels, members
<board>/010-<list>/020-<card>/card.yaml       id, title, labels, members, due, dueCompleted, tasks
<board>/010-<list>/020-<card>/description.md  the card body, plain Markdown
<board>/010-<list>/020-<card>/comments/       one file per comment: <date>-<time>-<author>.md
<board>/010-<list>/020-<card>/attachments/    the card's files
<board>/archive/, <board>/trash/        Planka's built-in lists; read-only
\`\`\`

Directory names carry an order prefix: filesystem sort order is Planka order, for lists and for
cards. The number is only a rank (gaps are normal); the slug after it is derived from the title.
The directory a card sits in is its list. Read \`board.yaml\` for the list, label and member names.

## Workflow

1. Edit files, then run \`npx planka-sync\` here. A non-zero exit means at least one \`error\`,
   \`blocked\` or \`failed\` line; fix what it names and run it again.
2. \`npx planka-sync validate\` checks the tree offline and lists pending changes.
   \`npx planka-sync sync --dry-run\` shows what a sync would do without doing it.
   \`npx planka-sync status\` summarises pending changes, conflicts and the last run.
3. On \`conflict\`, Planka's version is written beside your file as \`<file>.conflict\`. Merge it
   into your file, delete the \`.conflict\` file, run the sync again. \`sync --pull\` resolves
   every conflict in Planka's favour, \`sync --push\` in the local file's favour.
4. \`--json\` prints the run report as JSON; \`--yes\` allows a run that would trash more cards
   than the deletion cap; \`--renumber\` rewrites every order prefix from 010 in steps of 10.

## Editing rules

- **Existing card:** edit \`description.md\`, or \`title\`, \`labels\`, \`members\`, \`due\`,
  \`dueCompleted\`, \`tasks\` in \`card.yaml\`. Keep \`id\` and task \`id\`s as they are.
- **New card:** create \`<board>/<list>/<any-name>/card.yaml\` with at least \`title\` and no
  \`id\`. Add \`description.md\` for the body. Give the directory an order prefix to choose its
  spot (\`015-\` sorts between \`010-\` and \`020-\`); without one it goes to the bottom. The
  sync renames the directory to its canonical name.
- **Move:** move the card directory into another list directory of the same board.
- **Reorder:** rename the prefix so the directory sorts where you want it. Same for lists.
- **Delete:** remove the card directory; the card goes to Planka's trash, not away. Removing
  more directories than the deletion cap in one run is refused and they come back.
- **Tasks:** groups with items \`{ name, done }\`; a new item has no \`id\`; removing an item
  deletes it.
- **Comment:** add a \`.md\` file to \`comments/\`. Editing an existing comment file updates that
  comment; removing it deletes the comment. Planka refuses changes to other users' comments.
- **Attachment:** add a file to \`attachments/\`. Removing one is undone by the next sync;
  delete attachments in the Planka UI (Planka deletes them permanently).
- **New label or list:** append an entry without \`id\` to \`labels\` (\`name\`, \`color\`) or to
  \`lists\` (\`name\`) in \`board.yaml\`. Any other board.yaml edit is undone.
- Do not edit \`archive/\`, \`trash/\`, \`${STATE_DIR}/\` or this file. Every push is attributed
  to the Planka user that logged in.

## Direct API access

For what the tree cannot express (custom fields, board settings, users):
\`npx planka-sync api <METHOD> </api/path> [json-body]\` sends one request with the mirror's
credential and prints the JSON response. It has none of the safety nets above: \`DELETE\` is
permanent, and the next sync overwrites the tree with whatever the API left behind.
`;

const GITIGNORE = `# planka-sync: credential, manifest and base copies stay out of git.
/${STATE_DIR}/
`;

function writeVersioned(root: string, name: string, marker: string, content: string): boolean {
  const abs = join(root, name);
  if (existsSync(abs) && readFileSync(abs, "utf8").includes(marker)) return false;
  writeFileSync(abs, content);
  return true;
}

/** Writes AGENTS.md when missing or outdated and .gitignore when missing. Returns what changed. */
export function writeScaffold(root: string): string[] {
  const written: string[] = [];
  if (writeVersioned(root, "AGENTS.md", `agents v${AGENTS_VERSION};`, AGENTS_MD))
    written.push("AGENTS.md");
  const gitignore = join(root, ".gitignore");
  if (!existsSync(gitignore)) {
    writeFileSync(gitignore, GITIGNORE);
    written.push(".gitignore");
  } else if (!readFileSync(gitignore, "utf8").includes(STATE_DIR)) {
    writeFileSync(
      gitignore,
      `${readFileSync(gitignore, "utf8").replace(/\n?$/, "\n")}${GITIGNORE}`,
    );
    written.push(".gitignore (appended)");
  }
  return written;
}
